service: serverless-restapi

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage}
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  - ${file(yml/notes-functions.yml)}
  - ${file(yml/users-functions.yml)}

plugins:
  - serverless-offline # adding the plugin to be able to run the offline emulation
